Repository playcanvas/editor, pull requests merged in 2025-08, with the labels that each got.

#1356 Migrate How Do I popup to PCUI
  sass/editor/_editor-main.scss
  src/editor/help/howdoi-popup.ts
Labels: area: editor interface, enhancement

#1357 Remove unused sprite preview controls panel
  sass/editor/_editor-sprite-editor.scss
  src/editor/pickers/sprite-editor/sprite-editor-preview-panel.ts
Labels: area: editor interface, enhancement

#1368 Improved Error in Code Editor
  package-lock.json
  package.json
  src/code-editor/monaco/intellisense/attribute-autofill.ts
  src/workers/esm-script.worker.ts
Labels: area: scripts, enhancement

#1370 Clipboard - ability to copy/paste field values in Inspector
  sass/editor.scss
  sass/editor/_editor-clipboard.scss
  src/editor/assets/assets-context-menu.ts
  src/editor/entities/entities-context-menu.ts
  src/editor/index.ts
  src/editor/inspector/attributes-inspector.ts
  src/editor/storage/clipboard-context-menu.ts
Labels: enhancement

#1380 Rename Asset Tasks to Asset Import
  sass/editor.scss
  sass/editor/_editor-settings-asset-import.scss
  src/editor/attributes/reference/settings.ts
  src/editor/inspector/settings-panel.ts
  src/editor/inspector/settings-panels/asset-import.ts
Labels: area: editor interface

#1361 Improved Script Inspector Attribute Parsing UX
  package-lock.json
  package.json
  sass/editor/_editor-asset-script-inspector.scss
  src/code-editor/editor.ts
  src/editor/assets/handle-script-parse.ts
  src/editor/console/console.ts
  src/editor/inspector/assets/script.ts
  src/editor/toolbar/toolbar-code-editor.ts
  src/workers/esm-script.worker.ts
Labels: area: scripts, enhancement

#1395 Clipboard to respect enum/select type fields in Inspector
  src/editor/inspector/attributes-inspector.ts
  src/editor/storage/clipboard-context-menu.ts
Labels: enhancement

#1397 Clipboard icon buttons and tooltip - better styling
  sass/editor/_editor-clipboard.scss
  src/common/ui/tooltip.ts
  src/editor/inspector/attributes-inspector.ts
Labels: bug
